### ISSUE TITLE
Error While Installing

### ISSUE THREAD

**Issue by kyriacoscy** [ayudoo/odoo_business_relationships#2]
Hello,
While trying to install it on Odoo 15 I get the following error
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo15/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fd4babab940>, 'web.assets_backend')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 658, in _tag_template
    return self._tag_record(record)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 567, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 663, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 669, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_model.py", line 1935, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in _xmlid_lookup
  File "/opt/odoo15/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_model.py", line 1928, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.assets_backend

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo15/odoo/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo15/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1352, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo15/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing None:6, somewhere inside
<data inherit_id="web.assets_backend" name="Business Relationships Assets Backend">
    <xpath expr="//script[last()]" position="after">
      <link rel="stylesheet" href="/business_relationships/static/src/scss/backend.scss"/>
    </xpath>
  </data>
Any tips would be appreciated

**Comment by mjrk** [comment]
Thanks for your report. The module until now is Odoo 14 only and I update the README respectively. I will provide a Odoo 15 version until September, however, most probably earlier until end of next. I had some improvements planned but might skip them if you need the Odoo 15 version now. 

I'll leave this issue open until the then.

**Comment by kyriacoscy** [comment]
Hello sir and thank you for your prompt reply,

I would appreciate it if you could spare the time and make this module
compatible with odoo 15 now otherwise I will wait.
Thank you again and keep up the good work.

Best regards

Kyriacos Orphanides

**Comment by mjrk** [comment]
Hello @kyriacoscy 

I updated the module to Odoo 15 - the current main branch is the Odoo 15 version as noted in the README. Let me know if it works for you.

**Comment by kyriacoscy** [comment]
Hello sir,

I will have a go at it in a while and let you know.

Once again thanks and keep up the good work!!

**Comment by mjrk** [comment]
As there is a working odoo 15 and odoo 16 version (the latter on in testing use), I'll close this ticket now.

If you experience any issues with the newer versions, please open a new issue.
